import type { DeviceSpec, GradientPreset, ExportSize, SolidColorPreset } from "./types";

export const APP_NAME = "FrameLab";
export const GITHUB_REPO_URL = "https://github.com/awade12/framelab";
export const AUTHOR_NAME = "Andrew Wade";
export const AUTHOR_EMAIL = "awade75009@gmail.com";

export const devices: DeviceSpec[] = [
  {
    id: "iphone-15-pro-max",
    label: "iPhone 15 Pro Max",
    width: 1290,
    height: 2796,
    screenInset: { top: 20, right: 20, bottom: 20, left: 20 },
    cornerRadius: 110,
    frameRadius: { outer: "14%/6.5%", inner: "12.5%/5.8%" },
    notchWidth: 250,
    notchHeight: 70,
    hasIsland: true,
    colors: [
      {
        id: "black",
        label: "Black Titanium",
        frame: "#282828",
        frameColors: ["#4a4a4a", "#282828", "#1c1c1e", "#282828", "#4a4a4a"],
        screen: "#000",
      },
      {
        id: "natural",
        label: "Natural",
        frame: "#8C8883",
        frameColors: ["#AAA59E", "#8C8883", "#75726D", "#8C8883", "#AAA59E"],
        screen: "#000",
      },
      {
        id: "blue",
        label: "Blue",
        frame: "#2F3846",
        frameColors: ["#455163", "#2F3846", "#202630", "#2F3846", "#455163"],
        screen: "#000",
      },
      {
        id: "white",
        label: "White",
        frame: "#E3E3E4",
        frameColors: ["#F2F2F2", "#E3E3E4", "#D1D1D2", "#E3E3E4", "#F2F2F2"],
        screen: "#000",
      },
    ],
  },
  {
    id: "iphone-15-pro",
    label: "iPhone 15 Pro",
    width: 1179,
    height: 2556,
    screenInset: { top: 18, right: 18, bottom: 18, left: 18 },
    cornerRadius: 100,
    frameRadius: { outer: "14%/6.5%", inner: "12.5%/5.8%" },
    notchWidth: 230,
    notchHeight: 65,
    hasIsland: true,
    colors: [
      {
        id: "black",
        label: "Black Titanium",
        frame: "#282828",
        frameColors: ["#4a4a4a", "#282828", "#1c1c1e", "#282828", "#4a4a4a"],
        screen: "#000",
      },
      {
        id: "natural",
        label: "Natural",
        frame: "#8C8883",
        frameColors: ["#AAA59E", "#8C8883", "#75726D", "#8C8883", "#AAA59E"],
        screen: "#000",
      },
      {
        id: "blue",
        label: "Blue",
        frame: "#2F3846",
        frameColors: ["#455163", "#2F3846", "#202630", "#2F3846", "#455163"],
        screen: "#000",
      },
      {
        id: "white",
        label: "White",
        frame: "#E3E3E4",
        frameColors: ["#F2F2F2", "#E3E3E4", "#D1D1D2", "#E3E3E4", "#F2F2F2"],
        screen: "#000",
      },
    ],
  },
  {
    id: "iphone-14",
    label: "iPhone 14",
    width: 1170,
    height: 2532,
    screenInset: { top: 18, right: 18, bottom: 18, left: 18 },
    cornerRadius: 95,
    frameRadius: { outer: "14%/6.5%", inner: "12.5%/5.8%" },
    notchWidth: 210,
    notchHeight: 60,
    hasIsland: false,
    colors: [
      {
        id: "midnight",
        label: "Midnight",
        frame: "#2B3037",
        frameColors: ["#3A414A", "#2B3037", "#1E2227", "#2B3037", "#3A414A"],
        screen: "#000",
      },
      {
        id: "purple",
        label: "Purple",
        frame: "#E5DDEA",
        frameColors: ["#F0EAF5", "#E5DDEA", "#D5CDDA", "#E5DDEA", "#F0EAF5"],
        screen: "#000",
      },
      {
        id: "blue",
        label: "Blue",
        frame: "#A7C1D9",
        frameColors: ["#BDD3E8", "#A7C1D9", "#92AAC0", "#A7C1D9", "#BDD3E8"],
        screen: "#000",
      },
      {
        id: "red",
        label: "Red",
        frame: "#FC0324",
        frameColors: ["#FF3B55", "#FC0324", "#D4001A", "#FC0324", "#FF3B55"],
        screen: "#000",
      },
    ],
  },
  {
    id: "ipad-pro-12-9",
    label: 'iPad Pro 12.9"',
    width: 2048,
    height: 2732,
    screenInset: { top: 40, right: 40, bottom: 40, left: 40 },
    cornerRadius: 50,
    frameRadius: { outer: "3%/2.5%", inner: "2.5%/2%" },
    notchWidth: 0,
    notchHeight: 0,
    hasIsland: false,
    colors: [
      {
        id: "black",
        label: "Black",
        frame: "#1c1c1e",
        frameColors: ["#2c2c2e", "#1c1c1e", "#0d0d0d", "#1c1c1e", "#2c2c2e"],
        screen: "#000",
      },
      {
        id: "space-gray",
        label: "Space Gray",
        frame: "#4e4e50",
        frameColors: ["#636365", "#4e4e50", "#3a3a3c", "#4e4e50", "#636365"],
        screen: "#000",
      },
      {
        id: "silver",
        label: "Silver",
        frame: "#e0e0e0",
        frameColors: ["#ffffff", "#e0e0e0", "#d1d1d6", "#e0e0e0", "#ffffff"],
        screen: "#000",
      },
    ],
  },
  {
    id: "samsung-galaxy-s24-ultra",
    label: "Samsung Galaxy S24 Ultra",
    width: 1440,
    height: 3120,
    screenInset: { top: 16, right: 16, bottom: 16, left: 16 },
    cornerRadius: 40,
    frameRadius: { outer: "4%/2%", inner: "3.5%/1.8%" },
    notchWidth: 0,
    notchHeight: 0,
    hasIsland: false,
    colors: [
      {
        id: "titanium-black",
        label: "Titanium Black",
        frame: "#1a1a1a",
        frameColors: ["#2d2d2d", "#1a1a1a", "#0f0f0f", "#1a1a1a", "#2d2d2d"],
        screen: "#000",
      },
      {
        id: "titanium-gray",
        label: "Titanium Gray",
        frame: "#7a7a7a",
        frameColors: ["#8f8f8f", "#7a7a7a", "#656565", "#7a7a7a", "#8f8f8f"],
        screen: "#000",
      },
      {
        id: "titanium-violet",
        label: "Titanium Violet",
        frame: "#9b8aa5",
        frameColors: ["#b0a0ba", "#9b8aa5", "#867590", "#9b8aa5", "#b0a0ba"],
        screen: "#000",
      },
      {
        id: "titanium-yellow",
        label: "Titanium Yellow",
        frame: "#d4c87a",
        frameColors: ["#e5da90", "#d4c87a", "#c3b664", "#d4c87a", "#e5da90"],
        screen: "#000",
      },
    ],
  },
  {
    id: "samsung-galaxy-tab-s9",
    label: "Samsung Galaxy Tab S9",
    width: 1600,
    height: 2560,
    screenInset: { top: 35, right: 35, bottom: 35, left: 35 },
    cornerRadius: 40,
    frameRadius: { outer: "3%/2%", inner: "2.5%/1.5%" },
    notchWidth: 0,
    notchHeight: 0,
    hasIsland: false,
    colors: [
      {
        id: "graphite",
        label: "Graphite",
        frame: "#3c3c3c",
        frameColors: ["#4f4f4f", "#3c3c3c", "#292929", "#3c3c3c", "#4f4f4f"],
        screen: "#000",
      },
      {
        id: "beige",
        label: "Beige",
        frame: "#d9d0c5",
        frameColors: ["#ebe3d9", "#d9d0c5", "#c7beb3", "#d9d0c5", "#ebe3d9"],
        screen: "#000",
      },
    ],
  },
];

export const gradientPresets: GradientPreset[] = [
  { id: "sunset", label: "Sunset", from: "#ff7e5f", to: "#feb47b" },
  { id: "ocean", label: "Ocean", from: "#2b5876", to: "#4e4376" },
  { id: "mint", label: "Mint", from: "#00b09b", to: "#96c93d" },
  { id: "berry", label: "Berry", from: "#e1eec3", to: "#f05053" },
  { id: "royal", label: "Royal", from: "#141E30", to: "#243B55" },
  { id: "rose", label: "Rose", from: "#f4c4f3", to: "#fc67fa" },
];

export const solidColorPresets: SolidColorPreset[] = [
  { id: "white", label: "White", color: "#ffffff" },
  { id: "snow", label: "Snow", color: "#f8fafc" },
  { id: "pearl", label: "Pearl", color: "#f1f5f9" },
  { id: "mist", label: "Mist", color: "#e2e8f0" },
  { id: "silver", label: "Silver", color: "#cbd5e1" },
  { id: "slate", label: "Slate", color: "#94a3b8" },
  { id: "graphite", label: "Graphite", color: "#64748b" },
  { id: "charcoal", label: "Charcoal", color: "#475569" },
  { id: "steel", label: "Steel", color: "#334155" },
  { id: "midnight", label: "Midnight", color: "#1e293b" },
  { id: "ink", label: "Ink", color: "#0f172a" },
  { id: "black", label: "Black", color: "#000000" },
  { id: "cream", label: "Cream", color: "#fef3c7" },
  { id: "sand", label: "Sand", color: "#fde68a" },
  { id: "gold", label: "Gold", color: "#fbbf24" },
  { id: "amber", label: "Amber", color: "#f59e0b" },
  { id: "orange", label: "Orange", color: "#f97316" },
  { id: "tangerine", label: "Tangerine", color: "#fb923c" },
  { id: "coral", label: "Coral", color: "#ff7e5f" },
  { id: "peach", label: "Peach", color: "#fdba74" },
  { id: "salmon", label: "Salmon", color: "#fca5a5" },
  { id: "red", label: "Red", color: "#ef4444" },
  { id: "crimson", label: "Crimson", color: "#dc2626" },
  { id: "rose", label: "Rose", color: "#f43f5e" },
  { id: "pink", label: "Pink", color: "#ec4899" },
  { id: "blush", label: "Blush", color: "#f472b6" },
  { id: "magenta", label: "Magenta", color: "#d946ef" },
  { id: "purple", label: "Purple", color: "#8b5cf6" },
  { id: "violet", label: "Violet", color: "#7c3aed" },
  { id: "indigo", label: "Indigo", color: "#6366f1" },
  { id: "blue", label: "Blue", color: "#3b82f6" },
  { id: "sky", label: "Sky", color: "#0ea5e9" },
  { id: "cyan", label: "Cyan", color: "#06b6d4" },
  { id: "teal", label: "Teal", color: "#14b8a6" },
  { id: "emerald", label: "Emerald", color: "#10b981" },
  { id: "green", label: "Green", color: "#22c55e" },
  { id: "lime", label: "Lime", color: "#84cc16" },
  { id: "olive", label: "Olive", color: "#65a30d" },
  { id: "forest", label: "Forest", color: "#15803d" },
  { id: "pine", label: "Pine", color: "#134e4a" },
  { id: "mint", label: "Mint", color: "#6ee7b7" },
  { id: "aqua", label: "Aqua", color: "#5eead4" },
  { id: "ocean", label: "Ocean", color: "#0891b2" },
  { id: "navy", label: "Navy", color: "#1e3a8a" },
  { id: "cobalt", label: "Cobalt", color: "#2563eb" },
  { id: "royal", label: "Royal", color: "#4338ca" },
  { id: "plum", label: "Plum", color: "#581c87" },
  { id: "wine", label: "Wine", color: "#881337" },
  { id: "brick", label: "Brick", color: "#7c2d12" },
  { id: "brown", label: "Brown", color: "#78350f" },
  { id: "espresso", label: "Espresso", color: "#292524" },
  { id: "stone", label: "Stone", color: "#78716c" },
  { id: "taupe", label: "Taupe", color: "#a8a29e" },
  { id: "lavender", label: "Lavender", color: "#c4b5fd" },
  { id: "periwinkle", label: "Periwinkle", color: "#a5b4fc" },
  { id: "baby-blue", label: "Baby Blue", color: "#93c5fd" },
  { id: "powder", label: "Powder", color: "#bae6fd" },
  { id: "seafoam", label: "Seafoam", color: "#99f6e4" },
  { id: "sage", label: "Sage", color: "#86efac" },
  { id: "butter", label: "Butter", color: "#fef08a" },
  { id: "apricot", label: "Apricot", color: "#fed7aa" },
];

export const exportSizes: ExportSize[] = [
  {
    id: "iphone-1260",
    label: "iPhone 6.9\" portrait (1260×2736)",
    width: 1260,
    height: 2736,
    appStore: true,
  },
  {
    id: "iphone-1320",
    label: "iPhone 6.9\" portrait (1320×2868)",
    width: 1320,
    height: 2868,
    appStore: true,
  },
  {
    id: "iphone-1290",
    label: "iPhone 6.7\" portrait (1290×2796)",
    width: 1290,
    height: 2796,
    appStore: true,
  },
  {
    id: "iphone-1260-landscape",
    label: "iPhone landscape (2736×1260)",
    width: 2736,
    height: 1260,
    appStore: true,
  },
  {
    id: "iphone-1320-landscape",
    label: "iPhone landscape (2868×1320)",
    width: 2868,
    height: 1320,
    appStore: true,
  },
  {
    id: "iphone-1290-landscape",
    label: "iPhone landscape (2796×1290)",
    width: 2796,
    height: 1290,
    appStore: true,
  },
  {
    id: "ipad",
    label: "12.9\" iPad portrait (2048×2732)",
    width: 2048,
    height: 2732,
  },
  {
    id: "play-phone",
    label: "Play Store phone (1080×1920)",
    width: 1080,
    height: 1920,
  },
];

export const exportQualityOptions: {
  id: 1 | 2 | 3;
  label: string;
  description: string;
}[] = [
  { id: 1, label: "Standard", description: "Exact store size" },
  { id: 2, label: "High (2×)", description: "Retina-sharp PNG" },
  { id: 3, label: "Ultra (3×)", description: "Near-4K detail" },
];

export const PREVIEW_ASPECT_RATIO = {
  width: 1260,
  height: 2736,
} as const;
